#!/usr/bin/env bash
# use while loop to display "Best School" 10 times
#   On the 9th iteration display "Hi" before "Best School".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
